;;;; src/core/classes.lisp
;;;; Core CLOS classes (to be implemented via TDD)

(in-package #:project-juggler)

;;; Stub class definitions - will be implemented via TDD in Phase 1

(defclass project ()
  ((id :initarg :id :reader project-id)
   (name :initarg :name :reader project-name)
   (start :initarg :start :reader project-start)
   (end :initarg :end :reader project-end)
   (tasks :initform (make-hash-table :test 'eq) :accessor project-tasks)
   (resources :initform (make-hash-table :test 'eq) :accessor project-resources)
   (scenarios :initform nil :accessor project-scenarios)
   (current-scenario :initform :plan :accessor project-current-scenario)
   (baseline :initform nil :accessor project-baseline)
   (reports :initform (make-hash-table :test 'eq) :accessor project-reports))
  (:documentation "A project"))

(defun project-p (obj)
  "Check if object is a project"
  (typep obj 'project))

(defclass task ()
  ((id :initarg :id :reader task-id)
   (name :initarg :name :reader task-name)
   (project :initarg :project :reader task-project)
   (parent :initarg :parent :initform nil :accessor task-parent)
   (subtasks :initform nil :accessor task-subtasks)
   (dependencies :initform nil :accessor task-dependencies)
   (allocations :initform nil :accessor task-allocations)
   (effort :initarg :effort :initform nil :accessor task-effort)
   (duration :initarg :duration :initform nil :accessor task-duration)
   (start :initarg :start :initform nil :accessor task-start)
   (end :initarg :end :initform nil :accessor task-end)
   (priority :initarg :priority :initform 500 :accessor task-priority)
   (milestone :initarg :milestone :initform nil :accessor task-milestone-p)
   (complete :initarg :complete :initform 0 :accessor task-complete)
   (index :initarg :index :initform 0 :accessor task-index)
   (scheduled :initform nil :accessor task-scheduled-p)
   ;; TaskJuggler heuristic criticalness (for scheduling priority)
   (criticalness :initform 0.0 :accessor task-criticalness)
   (path-criticalness :initform 0.0 :accessor task-path-criticalness)
   ;; CPM critical path slots (calculated after scheduling)
   (early-start :initform nil :accessor task-early-start)
   (early-finish :initform nil :accessor task-early-finish)
   (late-start :initform nil :accessor task-late-start)
   (late-finish :initform nil :accessor task-late-finish)
   (slack :initform nil :accessor task-slack)
   ;; Bookings (actual time tracking)
   (bookings :initform nil :accessor task-bookings))
  (:documentation "A task"))

(defun task-p (obj)
  "Check if object is a task"
  (typep obj 'task))

(defclass resource ()
  ((id :initarg :id :reader resource-id)
   (name :initarg :name :reader resource-name)
   (project :initarg :project :reader resource-project)
   (parent :initarg :parent :initform nil :accessor resource-parent)
   (efficiency :initarg :efficiency :initform 1.0 :accessor resource-efficiency)
   (rate :initarg :rate :initform nil :accessor resource-rate)
   (limits :initform nil :accessor resource-limits)
   (criticalness :initform 0.0 :accessor resource-criticalness)
   (allocated-effort :initform 0.0 :accessor resource-allocated-effort)
   (available-effort :initform 0.0 :accessor resource-available-effort)
   ;; Bookings (actual time tracking)
   (bookings :initform nil :accessor resource-bookings))
  (:documentation "A resource"))

(defun resource-p (obj)
  "Check if object is a resource"
  (typep obj 'resource))

(defclass dependency ()
  ((source :initarg :source :reader dependency-source)
   (target-ref :initarg :target-ref :reader dependency-target-ref)
   (target :initarg :target :initform nil :accessor dependency-target)
   (type :initarg :type :initform :finish-start :reader dependency-type)
   (gap-duration :initarg :gap :initform nil :reader dependency-gap))
  (:documentation "A dependency between tasks"))

(defun dependency-p (obj)
  "Check if object is a dependency"
  (typep obj 'dependency))

(defclass allocation ()
  ((task :initarg :task :reader allocation-task)
   (resource-refs :initarg :resource-refs :reader allocation-resource-refs)
   (resources :initarg :resources :initform nil :accessor allocation-resources)
   (mandatory :initarg :mandatory :initform nil :reader allocation-mandatory-p))
  (:documentation "Resource allocation to task"))

(defun allocation-p (obj)
  "Check if object is an allocation"
  (typep obj 'allocation))

(defclass namespace ()
  ((name :initarg :name :reader namespace-name)
   (tasks :initform (make-hash-table :test 'eq) :accessor namespace-tasks)
   (resources :initform (make-hash-table :test 'eq) :accessor namespace-resources)
   (source-file :initarg :source-file :initform nil :reader namespace-source-file))
  (:documentation "Namespace for tasks and resources"))

(defclass session ()
  ((project :initarg :project :accessor session-project)
   (current-task :initform nil :accessor session-current-task)
   (changes :initform nil :accessor session-changes)
   (redo-stack :initform nil :accessor session-redo-stack))
  (:documentation "Project session"))

(defclass scenario ()
  ((id :initarg :id :reader scenario-id)
   (name :initarg :name :reader scenario-name)
   (parent :initarg :parent :initform nil :accessor scenario-parent)
   (enabled :initarg :enabled :initform t :accessor scenario-enabled-p))
  (:documentation "Project scenario"))

(defclass booking ()
  ((resource :initarg :resource :reader booking-resource)
   (task :initarg :task :reader booking-task)
   (start :initarg :start :reader booking-start)
   (end :initarg :end :reader booking-end)
   (amount :initarg :amount :reader booking-amount))
  (:documentation "Actual work booking"))

(defclass working-hours ()
  ((days :initarg :days :reader working-hours-days)
   (hours :initarg :hours :reader working-hours-hours))
  (:documentation "Working hours specification"))

(defclass calendar ()
  ((id :initarg :id :reader calendar-id)
   (working-hours :initarg :working-hours :reader calendar-working-hours)
   (holidays :initform nil :accessor calendar-holidays)
   (timezone :initarg :timezone :initform :utc :reader calendar-timezone))
  (:documentation "Calendar with working time and holidays"))

(defclass report ()
  ((id :initarg :id :reader report-id)
   (title :initarg :title :reader report-title)
   (format :initarg :format :reader report-format)
   (columns :initarg :columns :reader report-columns)
   (filter :initarg :filter :initform nil :reader report-filter)
   (sort-by :initarg :sort-by :initform nil :reader report-sort-by))
  (:documentation "Base report class"))

(defclass task-report (report)
  ()
  (:documentation "Task-focused report"))

(defclass resource-report (report)
  ()
  (:documentation "Resource-focused report"))

(defclass baseline ()
  ((name :initarg :name :reader baseline-name)
   (date :initarg :date :reader baseline-date)
   (tasks :initform (make-hash-table :test 'eq) :accessor baseline-tasks))
  (:documentation "Project baseline for EVM"))

(defclass baseline-task ()
  ((id :initarg :id :reader baseline-task-id)
   (name :initarg :name :reader baseline-task-name)
   (start :initarg :start :reader baseline-task-start)
   (end :initarg :end :reader baseline-task-end)
   (duration :initarg :duration :reader baseline-task-duration)
   (priority :initarg :priority :reader baseline-task-priority))
  (:documentation "Snapshot of task state in baseline"))

(defclass overallocation ()
  ((resource-id :initarg :resource-id :reader overallocation-resource-id)
   (date :initarg :date :reader overallocation-date)
   (load :initarg :load :reader overallocation-load))
  (:documentation "Resource over-allocation information"))
